FROM maven:3.8.4-openjdk-11 AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY . .

RUN mvn test

FROM maven:3.8.4-openjdk-11 AS runner

WORKDIR /app

COPY --from=builder /app /app

RUN mvn package -DskipTests

EXPOSE 8080

CMD ["java", "-jar", "/app/target/accenture-techhub-0.0.1-SNAPSHOT.war"]